name: Build
on: [workflow_dispatch]
jobs:
  build-on-openbsd:
    runs-on: macos-latest
    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/netbsd${{ matrix.version }}
          log: debug
          run: |
            run id
            run pwd
            run export -p
            touch aaa

      - run: printf '%s\n' "$VAGRANT_CWD"
