name: Build
on: [workflow_dispatch]

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/ubuntu1804
          run: |
            lscpu
