name: Build
on: [workflow_dispatch]

jobs:
  test:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Cache boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    - name: Run up
      run: vagrant up
    - name: ssh into box after boot
      run: |
        vagrant ssh -c "lscpu"
