name: Build
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [macos-latest]
    timeout-minutes: 360
 
    steps:
      - uses: actions/checkout@v2

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 5048
          ncpu: 4
          box: generic/ubuntu1804
          run: |
            lscpu
