name: Build
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [macos-13]
    timeout-minutes: 360
 
    steps:
      - uses: actions/checkout@v4
      - name: Cache boxes
      - uses: actions/cache@v2
        with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
      - name: Run up
        run: vagrant up
      - name: ssh into box after boot
        run: |
           vagrant ssh -c "python"
